{"name": "test_double_courier_api", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.", "trace": "self = <test_reg_double_courier_api.TestDoubleCourierApi object at 0x0000021663BDB110>, create_new_courier_and_del = {'firstName': 'saske', 'login': 'thbjufr', 'password': 'thbjufr'}\n\n    def test_double_courier_api(self, create_new_courier_and_del):\n        payload = create_new_courier_and_del\n        requests.post(Constants.URL + '/api/v1/courier', data=payload)\n        response_double = requests.post(Constants.URL + '/api/v1/courier', data=payload)\n        r_double = response_double.json()\n        assert response_double.status_code == 409\n>       assert r_double['message'] == \"Этот логин уже используется\"\nE       AssertionError: assert 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE         - Этот логин уже используется\nE         + Этот логин уже используется. Попробуйте другой.\n\ntests\\test_reg_double_courier_api.py:13: AssertionError"}, "start": 1707330200333, "stop": 1707330201981, "uuid": "ea43a945-0bc7-49fb-9bf4-39ad4025ac01", "historyId": "290c23b57010c2d5a414b9b247f4dca9", "testCaseId": "290c23b57010c2d5a414b9b247f4dca9", "fullName": "tests.test_reg_double_courier_api.TestDoubleCourierApi#test_double_courier_api", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_reg_double_courier_api"}, {"name": "subSuite", "value": "TestDoubleCourierApi"}, {"name": "host", "value": "DESKTOP-1B681S0"}, {"name": "thread", "value": "28248-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_reg_double_courier_api"}]}